DEFAULT_BUS_CAPACITY = 50
MIN_BUS_CAPACITY = 20
MAX_BUS_CAPACITY = 100

NIGERIA_COUNTRY_CODE = "+234"
PHONE_NUMBER_LENGTH = 15

GPS_UPDATE_INTERVAL_SECONDS = 30
TERMINAL_RADIUS_METERS = 100
CLOSE_PROXIMITY_METERS = 500
MAX_GPS_ACCURACY_METERS = 50

DEFAULT_NOTIFICATION_WINDOW = 10
MAX_SHIFT_DURATION_HOURS = 12
TOKEN_EXPIRE_MIN = 1440

STATUS_ACTIVE = "active"
STATUS_INACTIVE = "inactive"
STATUS_PENDING = "pending"
STATUS_VERIFIED = "verified"

EMPLOYEE_ID_PREFIX = "DRV"
EMPLOYEE_ID_MIN_LENGTH = 6

BUS_NUMBER_PREFIX = "BRT-"
BUS_NUMBER_MIN_LENGTH = 7